name: Build APK

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL'
        required: false
        default: 'https://github.com/shiveshnavin/socio-search'
      profile:
        description: 'Build Profile'
        required: false
        type: choice
        options:
        - development
        - production
        - preview
        default: development
      expo_token:
        description: 'Expo Token'
        required: false
      apk_upload_url:
        description: 'APK Upload URL (optional)'
        required: false

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Docker Container to Build APK
      id: build_apk
      run: |
        # Run the docker command to build the APK
        docker run --rm \
          -v $(pwd)/local-builds:/app/builds \
          semibit/react-native-build \
          ${{ github.event.inputs.repo_url }} \
          ${{ github.event.inputs.profile }} \
          ${{  github.event.inputs.expo_token || secrets.EXPO_TOKEN }} \
          ${{ github.event.inputs.apk_upload_url }}

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-apk
        path: ./local-builds/*.apk

